name: flutter_bloc_basic
description: flutter bloc basic
version: 0.1.6
homepage: https://github.com/moon-motorcycle/flutter_bloc_basic

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  # Bloc 框架 https://bloclibrary.dev/#/zh-cn/
  bloc: ^7.2.1
  flutter_bloc: ^7.1.0
  # HTTP https://pub.dev/packages/dio
  dio: ^4.0.3
  # https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.1.1
  # https://pub.dev/packages/logger
  logger: ^1.1.0
  # 网络图片加载 https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.1.0+1
  # 轮播 https://pub.dev/packages/card_swiper
  card_swiper: ^1.0.4
  # key-value存储 https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.8
  # Toast https://pub.dev/packages/fluttertoast
  fluttertoast: ^8.0.8
  # 路由管理 https://pub.dev/packages/fluro
  fluro: ^2.0.3
  # 列表刷新加载 https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # 弹窗控件 https://pub.dev/packages/flutter_smart_dialog
  flutter_smart_dialog: ^3.0.2
  # 视频播放
  # https://pub.dev/packages/video_player
  video_player: ^2.2.10
  # 音频播放 https://pub.dev/packages/audioplayers
  audioplayers: ^0.20.1
  # https://pub.dev/packages/flutter_html
  flutter_html: ^2.2.0
  # https://pub.dev/packages/chewie  flutter_html 中包含以下依赖
  # chewie: ^1.2.2
  # 屏幕适配 https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

